import { existsSync, readFileSync, writeFileSync, mkdirSync, cpSync, readdirSync, statSync } from "fs";
import { join, basename } from "path";
import { homedir } from "os";
import { BaseAdapter } from "./base.mjs";
import { readMcpManifest, toCodexToml, upsertTomlTable } from "../mcp.mjs";
import { ensureProjectAgents } from "../project-guidance.mjs";

export class CodexAdapter extends BaseAdapter {
  constructor() {
    const defaultHome = join(homedir(), ".codex");
    super("codex", defaultHome, "CODEX_HOME", "codex");
  }

  async init(cwd, projectHome) {
    const configDir = this.getConfigDir(cwd, projectHome);
    const dirs = ["agents", "skills", "plugins"];
    for (const dir of dirs) {
      this.ensureDir(join(configDir, dir));
    }
    ensureProjectAgents(cwd);
  }

  async installAgent(cwd, agentFile, agentName, projectHome) {
    const content = readFileSync(agentFile, "utf8");
    const toml = this.toToml(content, agentName);
    const destDir = join(this.getConfigDir(cwd, projectHome), "agents");
    this.ensureDir(destDir);
    writeFileSync(join(destDir, `${agentName}.toml`), toml);
    console.log(`  Installed agent: ${agentName}`);
  }

  async installSkill(cwd, skillDir, skillName, projectHome) {
    const destDir = join(this.getConfigDir(cwd, projectHome), "skills", skillName);
    this.ensureDir(destDir);
    cpSync(skillDir, destDir, { recursive: true });
    console.log(`  Installed skill: ${skillName}`);
  }

  async installCommand(cwd, commandFile, commandName, projectHome) {
    const destDir = join(this.getConfigDir(cwd, projectHome), "skills", commandName);
    this.ensureDir(destDir);
    cpSync(commandFile, join(destDir, "SKILL.md"));
    console.log(`  Installed command as skill: ${commandName}`);
  }

  async installMcp(cwd, mcpFile, mcpName, projectHome) {
    const manifest = readMcpManifest(mcpFile);
    const configPath = join(this.getConfigDir(cwd, projectHome), "config.toml");
    upsertTomlTable(configPath, `[mcp_servers.${mcpName}]`, toCodexToml(manifest));
    console.log(`  Installed MCP: ${mcpName}`);
  }

  async installPlugin(cwd, pluginDir, pluginName, projectHome) {
    const configDir = this.getConfigDir(cwd, projectHome);

    const agentsDir = join(pluginDir, "agents");
    if (existsSync(agentsDir)) {
      for (const entry of readdirSync(agentsDir)) {
        if (entry.endsWith(".md")) {
          const agentName = basename(entry, ".md");
          const content = readFileSync(join(agentsDir, entry), "utf8");
          const toml = this.toToml(content, agentName);
          const destDir = join(configDir, "agents");
          this.ensureDir(destDir);
          writeFileSync(join(destDir, `${agentName}.toml`), toml);
          console.log(`  Installed agent: ${agentName}`);
        }
      }
    }

    const skillsDir = join(pluginDir, "skills");
    if (existsSync(skillsDir)) {
      const destDir = join(configDir, "skills");
      this.ensureDir(destDir);
      for (const entry of readdirSync(skillsDir)) {
        const skillPath = join(skillsDir, entry);
        if (statSync(skillPath).isDirectory()) {
          cpSync(skillPath, join(destDir, entry), { recursive: true });
          console.log(`  Installed skill: ${entry}`);
        }
      }
    }
  }

  async generate(cwd, componentsDir, projectHome) {
    console.log("Generating Codex CLI artifacts...");
    const configDir = this.getConfigDir(cwd, projectHome);

    const agentsSrc = join(componentsDir, "agents");
    if (existsSync(agentsSrc)) {
      const destDir = join(configDir, "agents");
      this.ensureDir(destDir);
      this.walkAndConvert(agentsSrc, destDir);
    }

    const pluginsSrc = join(componentsDir, "plugins");
    if (existsSync(pluginsSrc)) {
      for (const entry of readdirSync(pluginsSrc)) {
        const pluginDir = join(pluginsSrc, entry);
        if (statSync(pluginDir).isDirectory()) {
          await this.installPlugin(cwd, pluginDir, entry, projectHome);
        }
      }
    }
    await this.generatePortable(cwd, componentsDir, projectHome);
    this.generateMarketplace(cwd, componentsDir, projectHome);
    console.log("Done.");
  }

  walkAndConvert(src, dest) {
    for (const entry of readdirSync(src)) {
      const fullPath = join(src, entry);
      if (statSync(fullPath).isDirectory()) {
        this.walkAndConvert(fullPath, dest);
      } else if (entry.endsWith(".md")) {
        const agentName = basename(entry, ".md");
        const content = readFileSync(fullPath, "utf8");
        writeFileSync(join(dest, `${agentName}.toml`), this.toToml(content, agentName));
      }
    }
  }

  toToml(content, name) {
    const lines = [];
    lines.push(`# ${name} agent`);
    lines.push(`# Auto-generated by nstack`);
    lines.push("");

    if (content.startsWith("---")) {
      const end = content.indexOf("\n---", 3);
      if (end !== -1) {
        const block = content.slice(3, end).trim();
        for (const line of block.split("\n")) {
          const m = line.match(/^(\w[\w-]*):\s*(.*)/);
          if (m) {
            const key = m[1];
            let val = m[2].trim();
            if (key === "model") {
              const map = { opus: "gpt-5", sonnet: "gpt-5-mini", haiku: "gpt-5-nano", inherit: "gpt-5" };
              val = map[val] || val;
            }
            lines.push(`${key} = "${val}"`);
          }
        }
        lines.push("");
        const body = content.slice(end + 4).trim();
        if (body) {
          lines.push("[instructions]");
          lines.push('body = """');
          lines.push(body.replace(/"""/g, '\\"\\"\\"'));
          lines.push('"""');
        }
      }
    } else {
      lines.push(`name = "${name}"`);
      lines.push("");
      lines.push("[instructions]");
      lines.push('body = """');
      lines.push(content.replace(/"""/g, '\\"\\"\\"'));
      lines.push('"""');
    }
    return lines.join("\n") + "\n";
  }

  generateMarketplace(cwd, componentsDir, projectHome) {
    const pluginsDir = join(componentsDir, "plugins");
    if (!existsSync(pluginsDir)) return;
    const plugins = [];
    for (const entry of readdirSync(pluginsDir)) {
      const pluginDir = join(pluginsDir, entry);
      if (statSync(pluginDir).isDirectory()) {
        const pj = join(pluginDir, ".claude-plugin", "plugin.json");
        if (existsSync(pj)) {
          const m = JSON.parse(readFileSync(pj, "utf8"));
          plugins.push({ name: m.name || entry, version: m.version || "1.0.0", description: m.description || "" });
        }
      }
    }
    const destDir = join(this.getConfigDir(cwd, projectHome), "plugins");
    this.ensureDir(destDir);
    writeFileSync(join(destDir, "marketplace.json"), JSON.stringify({ plugins }, null, 2) + "\n");
  }
}
